import type { DiagnosticsProvider, ProviderResult } from "../provider";
import type { DiagnosticsReport } from "../../types/report";
import { SEVERITY_LABELS } from "../../constants";

const TAG = "[diagnostics:resend]";

const sentErrorIds = new Set<string>();
const MAX_SENT_CACHE = 200;

function log(level: "info" | "warn" | "error", msg: string): void {
  const entry = `${TAG} ${msg}`;
  if (level === "error") console.error(entry);
  else if (level === "warn") console.warn(entry);
  else console.log(entry);
}

function getEnv(name: string): string | null {
  if (typeof process === "undefined") return null;
  const val = process.env[name];
  if (!val || val.trim() === "") return null;
  return val.trim();
}

function isConfigured(): boolean {
  return (
    getEnv("RESEND_API_KEY") !== null &&
    getEnv("DIAGNOSTICS_EMAIL_FROM") !== null &&
    getEnv("DIAGNOSTICS_EMAIL_TO") !== null
  );
}

function buildSubjectLine(report: DiagnosticsReport): string {
  return `\u{1F6A8} SPNET ${report.classification.label} [${report.errorId}]`;
}

function buildPlainText(report: DiagnosticsReport): string {
  const severityLabel =
    SEVERITY_LABELS[report.classification.severity] || report.classification.severity;

  const lines: string[] = [
    `SP NET Diagnostics Report`,
    ``,
    `Error ID: ${report.errorId}`,
    `Severity: ${severityLabel}`,
    `Category: ${report.classification.category}`,
    `Label: ${report.classification.label}`,
    `Timestamp: ${report.timestamp}`,
    `Route: ${report.route}`,
    ``,
    `Summary:`,
    report.classification.summary,
    ``,
    `Likely Causes:`,
    ...report.classification.likelyCauses.map((c) => `  \u2022 ${c}`),
    ``,
    `Suggested Resolution:`,
    ...report.classification.suggestedResolution.map((r) => `  \u2022 ${r}`),
    ``,
    `---`,
    ``,
    `Browser: ${report.environment.browser} (${report.environment.browserVersion})`,
    `OS: ${report.environment.os}`,
    `Device: ${report.environment.device}`,
    `Viewport: ${report.environment.viewport.width}x${report.environment.viewport.height}`,
    `Language: ${report.environment.viewport.language}`,
    `Timezone: ${report.environment.viewport.timezone}`,
    ``,
    `Session ID: ${report.session.sessionId}`,
    `Session Started: ${report.session.startedAt}`,
    `Errors This Session: ${report.session.errorsThisSession}`,
    ``,
    `Original Error:`,
    report.error.message,
    ``,
  ];

  if (report.error.stack) {
    lines.push(`Stack Trace:`);
    lines.push(report.error.stack);
    lines.push(``);
  }

  lines.push(`Generated by SP NET Diagnostics SDK v${report.metadata.sdkVersion}`);

  return lines.join("\n");
}

async function renderHtml(report: DiagnosticsReport): Promise<string> {
  try {
    const { render } = await import("@react-email/render");
    const { default: DiagnosticsEmail } = await import("./email-template");
    const html = await render(DiagnosticsEmail({ report }));
    return html;
  } catch (err) {
    log("error", `Failed to render email template: ${err}`);
    return "";
  }
}

async function sendEmail(
  report: DiagnosticsReport,
  html: string
): Promise<ProviderResult> {
  const apiKey = getEnv("RESEND_API_KEY");
  const fromAddress = getEnv("DIAGNOSTICS_EMAIL_FROM");
  const toAddress = getEnv("DIAGNOSTICS_EMAIL_TO");

  if (!apiKey || !fromAddress || !toAddress) {
    return {
      success: false,
      providerId: "resend",
      error: "Missing environment variables: RESEND_API_KEY, DIAGNOSTICS_EMAIL_FROM, or DIAGNOSTICS_EMAIL_TO",
      timestamp: new Date().toISOString(),
    };
  }

  const subject = buildSubjectLine(report);
  const text = buildPlainText(report);

  const payload: Record<string, unknown> = {
    from: `SP NET Diagnostics <${fromAddress}>`,
    to: [toAddress],
    subject,
    text,
  };

  if (html && html.length > 0) {
    payload.html = html;
  }

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const body = await res.text();
      log("error", `Resend API returned ${res.status}: ${body}`);
      return {
        success: false,
        providerId: "resend",
        error: `Resend API error: ${res.status}`,
        timestamp: new Date().toISOString(),
      };
    }

    return {
      success: true,
      providerId: "resend",
      timestamp: new Date().toISOString(),
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown network error";
    log("error", `Network error sending email: ${message}`);
    return {
      success: false,
      providerId: "resend",
      error: message,
      timestamp: new Date().toISOString(),
    };
  }
}

export const ResendProvider: DiagnosticsProvider = {
  name: "Resend Email",
  id: "resend",

  isAvailable(): boolean {
    return isConfigured();
  },

  async send(report: DiagnosticsReport): Promise<ProviderResult> {
    if (sentErrorIds.has(report.errorId)) {
      log("info", `Skipped duplicate: ${report.errorId}`);
      return {
        success: true,
        providerId: "resend",
        timestamp: new Date().toISOString(),
      };
    }

    log("info", `Sending email for ${report.errorId}`);

    const html = await renderHtml(report);
    const result = await sendEmail(report, html);

    if (result.success) {
      sentErrorIds.add(report.errorId);

      if (sentErrorIds.size > MAX_SENT_CACHE) {
        const firstId = sentErrorIds.values().next().value;
        if (firstId) sentErrorIds.delete(firstId);
      }

      log("info", `Sent email for ${report.errorId}`);
    } else {
      log("error", `Failed to send email for ${report.errorId}: ${result.error}`);
    }

    return result;
  },
};
