import type { DiagnosticsReport, FormattedReport, ReportSection } from "../types/report";
import { SEVERITY_LABELS, CATEGORY_LABELS } from "../constants";

export function formatReport(report: DiagnosticsReport): FormattedReport {
  const sections: ReportSection[] = [
    {
      title: "Error Details",
      entries: [
        { label: "Error ID", value: report.errorId },
        { label: "Detected", value: report.timestamp },
        { label: "Route", value: report.route },
        {
          label: "Error Type",
          value: CATEGORY_LABELS[report.classification.category] || report.classification.category,
        },
        {
          label: "Severity",
          value: SEVERITY_LABELS[report.classification.severity] || report.classification.severity,
        },
      ],
    },
    {
      title: "Classification",
      entries: [
        { label: "Label", value: report.classification.label },
        { label: "Summary", value: report.classification.summary },
        ...report.classification.likelyCauses.map((cause) => ({
          label: "Likely Cause",
          value: cause,
        })),
        ...report.classification.suggestedResolution.map((resolution) => ({
          label: "Suggested Resolution",
          value: resolution,
        })),
      ],
    },
    {
      title: "Environment",
      entries: [
        { label: "Browser", value: report.environment.browser },
        { label: "OS", value: report.environment.os },
        { label: "Device", value: report.environment.device },
        { label: "Framework", value: report.environment.runtime.framework },
        {
          label: "Viewport",
          value: `${report.environment.viewport.width}x${report.environment.viewport.height}`,
        },
        {
          label: "Screen",
          value: `${report.environment.viewport.screenWidth}x${report.environment.viewport.screenHeight}`,
        },
        { label: "Language", value: report.environment.viewport.language },
        { label: "Timezone", value: report.environment.viewport.timezone },
      ],
    },
    {
      title: "Session",
      entries: [
        { label: "Session ID", value: report.session.sessionId },
        { label: "Session Started", value: report.session.startedAt },
        {
          label: "Errors This Session",
          value: String(report.session.errorsThisSession),
        },
        { label: "Recovered", value: report.session.recovered ? "Yes" : "No" },
        {
          label: "Recovery Attempts",
          value: String(report.session.recoveryAttempts),
        },
        {
          label: "Session Duration",
          value: `${Math.round(report.session.duration / 1000)}s`,
        },
      ],
    },
  ];

  if (report.error.stack) {
    sections.push({
      title: "Stack Trace",
      entries: [{ label: "Stack", value: report.error.stack }],
    });
  }

  return {
    header: `SP NET Error Report — ${report.errorId}`,
    sections,
    footer: `Generated by SP NET Diagnostics SDK v${report.metadata.sdkVersion}`,
  };
}

export function formatReportToPlainText(report: DiagnosticsReport): string {
  const formatted = formatReport(report);
  const lines: string[] = [];

  lines.push(formatted.header);
  lines.push("=".repeat(formatted.header.length));
  lines.push("");

  for (const section of formatted.sections) {
    lines.push(`[${section.title}]`);
    for (const entry of section.entries) {
      if (entry.value.includes("\n")) {
        lines.push(`${entry.label}:`);
        lines.push(entry.value);
      } else {
        lines.push(`${entry.label}: ${entry.value}`);
      }
    }
    lines.push("");
  }

  lines.push(formatted.footer);
  return lines.join("\n");
}
